#!/bin/sh

# Full path to composer registry install
REGISTRY_PATH="/data/registry"
# Webroot is set to /public folder in composer registry install directory
WEBROOT="$REGISTRY_PATH/public"

cd "$REGISTRY_PATH"
/bin/git fetch --all
/bin/git reset --hard origin/master
/usr/local/bin/composer update
/usr/local/bin/composer run-script setup
/sbin/selinuxenabled
if [ $? -eq 0 ] ; then
    /sbin/restorecon -Rv "$WEBROOT"
fi
